### PR TITLE
move common prefix logic to base class

### PR DESCRIPTION
**Pull request by dirk-thomas**
Refactoring to deduplicate logic. No functional change.

**Update:** see comments below for functional changes in the third commit.

Connect to ros2/ros2#364.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The third commit addresses #109.

Since this introduces a significant change I am asking for a re-review.

**Comment by wjwwood** [comment]
Doh, I didn't see ded89e7. Let me look at it again...

**Comment by dirk-thomas** [comment]
Sorry, the latest change just added some "extra care" for Windows: https://github.com/ament/ament_tools/commit/ded89e7c1fa1dd0d24c26f72fa62ce966aa92ea2#diff-3e23bf3d285e5a32da12025ac88c215aR49

**Comment by dirk-thomas** [comment]
> I don't see anything wrong with the changes, but I also don't clearly understand why d896162 fixes #109.

The refactoring commits to change anything. Only the third commit makes functional changes (introducing `get_setup_arguments_with_context`) which fixes the problem mentioned in the referenced ticket. 

> Is `get_setup_arguments` used anymore or is it meant to be completely replaced with `get_setup_arguments_with_context`?

`get_setup_arguments` is still being used. E.g. when a pure Python package is being handled. Since there are no dependencies declared the logic is being run with the current interpreter. The function is also being used from `get_setup_arguments_with_context`.

`get_setup_arguments_with_context` is being used when a package declared dependencies in its manifest. Then a custom environment including all build dependencies is generated and a separate Python interpreter is started to extract the information from the `setup()` call.

**Pull request merged**
