### PR TITLE
invoke CTest with dashboard test summary

### PR DESCRIPTION
**Pull request by dirk-thomas**
http://ci.ros2.org/job/ros2_batch_ci_windows/358/

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The third commit adds the result file type as a second extension to the filename.

**Comment by jacquelinekay** [comment]
I am reviewing this right now.

**Comment by jacquelinekay** [comment]
Can you explain what's happening in the latest Jenkins job for the `gtest_location` branches for Windows?

**Comment by jacquelinekay** [comment]
Nevermind, ros2/ros2/issues/106 explains it.

**Comment by jacquelinekay** [comment]
Hmm, the double-reporting issue really bothers me but I don't know enough about these testing frameworks to suggest a fix.

Is there a way to get Jenkins to only the report failed/not run CTest results? Or is this not enough information/not a complete representation of the test suite, and why?

**Comment by dirk-thomas** [comment]
Well, you kind of need to be able to see all tests. Otherwise you don't know if a certain test was actually run and what its output was.

**Comment by jacquelinekay** [comment]
Ok, what I meant to ask is: why can't Jenkins just report the CTest dashboard and ignore the Gtest/Jtest results? It seems to me that the CTest results are a superset of the test results we're interested in, but I could be wrong (since again, I don't know much about the features of the different frameworks).

**Comment by dirk-thomas** [comment]
We could only use the CTest result file. But that would hide all all GTest / Nosetests specific "sub-tests" from the user. It would only report a single passed / failed test for a nosetests invocation.

**Comment by jacquelinekay** [comment]
Got it. I guess when it comes to tests more information is always better
than less.

+1

**Pull request merged**
