### PR TITLE
add --retest-until-fail and --retest-until-pass options

### PR DESCRIPTION
**Pull request by dirk-thomas**
`--retest-until-fail N` will retry running all tests up to N times if all tests pass.

`--retest-until-pass N` will retry all (or for CTest only the failed) tests up to N times if any test fails.

Connect to ros2/ros2#224

### CODE REVIEW

**Comment by wjwwood** [comment]
> Connect to #224

Which repository is that supposed to be linked to?

**Comment by dirk-thomas** [comment]
ros2/ros2#224

**Comment by wjwwood** [comment]
Other than possibly putting the iteration number out of the target number in the retry messages, +1.

**Comment by dirk-thomas** [comment]
Good point - updated.

**Pull request merged**
