### PR TITLE
use python3.5 for travis testing

### PR DESCRIPTION
**Pull request by wjwwood**
Since we now use pydocstyle from python3.5 this is required.

### CODE REVIEW

**Comment by wjwwood** [comment]
Also, apparently install `pydocstyle`.

**Comment by wjwwood** [comment]
@dirk-thomas should we turn off pep257 tests? There are more than two hundred failures right now.

**Comment by dirk-thomas** [comment]
I think it would be good to continue testing the code which already conforms. Maybe blacklist the third-party code which doesn't?

**Comment by wjwwood** [comment]
Any idea why it is including those other ones? I thought this line should limit it to this package's source: https://github.com/ament/ament_tools/blob/master/test/test_pep257.py#L19

**Comment by dirk-thomas** [comment]
It does so for me locally. So it might be related to the travis script.

**Comment by wjwwood** [comment]
@dirk-thomas how did you determine that it is only checking those folders locally?

**Comment by dirk-thomas** [comment]
Because it passed?

**Comment by wjwwood** [comment]
I think this is a regression of ament/ament_lint#49, see: https://github.com/ament/ament_lint/pull/49/files#r67576895

**Comment by wjwwood** [comment]
@dirk-thomas but that doesn't ensure that it only checks those directories, only that there are no other directories which need to be ignored.

**Comment by dirk-thomas** [comment]
That's true. I thought the layout would be the same locally then in Travis.

If I place additional files in a new subfolder under `ament_tools` they are being linted by PEP257 which shouldn't be the case.

**Comment by wjwwood** [comment]
Ok, I'll look into a fix later if you don't have time.

**Comment by dirk-thomas** [comment]
Fixed in ament/ament_lint#57.

**Comment by dirk-thomas** [comment]
@wjwwood FYI cca1c22f1639c48868789d63a07903a8607af920

**Comment by wjwwood** [comment]
Thanks, I'll see if it works in f4c4c8f.

**Comment by wjwwood** [comment]
lgtm, I'll revert f4c4c8f and +1 the fix.

**Comment by dirk-thomas** [comment]
+1 (with squashing)

**Pull request merged**
