### PR TITLE
fixing quoting to work with whitespace in the paths

### PR DESCRIPTION
**Pull request by tfoote**
Connects to ament/ament_tools#27

### CODE REVIEW

**Comment by wjwwood** [comment]
+1

**Comment by esteve** [comment]
+1

**Comment by dirk-thomas** [comment]
Are these lines also affected? https://github.com/ament/ament_tools/blob/62e1aa5b6a9988923145e7f595640dae01324571/ament_tools/build_types/ament_python.py#L118-L121

**Comment by tfoote** [comment]
@dirk-thomas Fixed that line and fixed up broken test after merge.

**Comment by dirk-thomas** [comment]
I tried a workspace with the patch from this PR as well as ament/ament_package#10 but couldn't even get past the first couple of packages. Were you able to build a workspace using this PR?

**Comment by dirk-thomas** [comment]
I was able to build the full workspace (with OpenSplice being ignored for now).

**Pull request merged**
