### PR TITLE
always print test output to console

### PR DESCRIPTION
**Pull request by dirk-thomas**
Connects to ament/ament_cmake#10

### CODE REVIEW

**Comment by wjwwood** [comment]
+1, however you can also put the ARGS before the ament call since it is interpreted as an env variable.

**Comment by dirk-thomas** [comment]
The only two references I could find on this are:
* http://public.kitware.com/pipermail/cmake/2013-August/055423.html
* http://stackoverflow.com/questions/3065220/ctest-with-multiple-commands

which both mention passing `ARGS` as a argument to `make test`.

**Comment by wjwwood** [comment]
I think the pull request implementation is fine, but I was just pointing out that you can set the `ARGS` just like you can do `VERBOSE` for `make`. User's might find it surprising that `ctest` is always called with `-V`, also as designed you cannot disable `-V` being passed to `ctest`. Here's an example of what I'm talking about:

```
~/ros2_ws$ ./src/ament/ament_tools/scripts/ament.py test ./src --only connext_cmake_module
[ ... ]
+++ Testing 'connext_cmake_module'
==> '. /home/william/ros2_ws/build/connext_cmake_module/ament_cmake__test.sh && /usr/bin/make test' in '/home/william/ros2_ws/build/connext_cmake_module'
Running tests...
Test project /home/william/ros2_ws/build/connext_cmake_module
    Start 1: copyright
1/2 Test #1: copyright ........................***Failed    0.22 sec
    Start 2: lint_cmake
2/2 Test #2: lint_cmake .......................   Passed    0.17 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =   0.39 sec

The following tests FAILED:
	  1 - copyright (Failed)
Errors while running CTest
make: *** [test] Error 8

Stopping with package 'connext_cmake_module'
~/ros2_ws$ ARGS=-V ./src/ament/ament_tools/scripts/ament.py test ./src --only connext_cmake_module
[ ... ]
+++ Testing 'connext_cmake_module'
==> '. /home/william/ros2_ws/build/connext_cmake_module/ament_cmake__test.sh && /usr/bin/make test' in '/home/william/ros2_ws/build/connext_cmake_module'
Running tests...
UpdateCTestConfiguration  from :/home/william/ros2_ws/build/connext_cmake_module/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/william/ros2_ws/build/connext_cmake_module/DartConfiguration.tcl
Test project /home/william/ros2_ws/build/connext_cmake_module
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: copyright

1: Test command: /usr/bin/python3 "/home/william/ros2_ws/install/share/ament_cmake_test/cmake/run_test.py" "/home/william/ros2_ws/build/connext_cmake_module/test_results/connext_cmake_module/copyright.xml" "--output-file" "/home/william/ros2_ws/build/connext_cmake_module/ament_copyright/copyright.txt" "--command" "/home/william/ros2_ws/install/bin/ament_copyright" "--xunit-file" "/home/william/ros2_ws/build/connext_cmake_module/test_results/connext_cmake_module/copyright.xml"
1: Test timeout computed to be: 60
1: -- run_test.py: invoke following command in '/media/psf/Home/ros2/src/ros2/rmw_connext/connext_cmake_module':
1:  - /home/william/ros2_ws/install/bin/ament_copyright --xunit-file /home/william/ros2_ws/build/connext_cmake_module/test_results/connext_cmake_module/copyright.xml
1: -- run_test.py: verify result file '/home/william/ros2_ws/build/connext_cmake_module/test_results/connext_cmake_module/copyright.xml'
1/2 Test #1: copyright ........................***Failed    0.21 sec
test 2
    Start 2: lint_cmake

2: Test command: /usr/bin/python3 "/home/william/ros2_ws/install/share/ament_cmake_test/cmake/run_test.py" "/home/william/ros2_ws/build/connext_cmake_module/test_results/connext_cmake_module/lint_cmake.xml" "--output-file" "/home/william/ros2_ws/build/connext_cmake_module/ament_lint_cmake/lint_cmake.txt" "--command" "/usr/bin/python3" "/home/william/ros2_ws/install/share/ament_lint_cmake/cmake/../../../bin/ament_lint_cmake" "--xunit-file" "/home/william/ros2_ws/build/connext_cmake_module/test_results/connext_cmake_module/lint_cmake.xml"
2: Test timeout computed to be: 60
2: -- run_test.py: invoke following command in '/media/psf/Home/ros2/src/ros2/rmw_connext/connext_cmake_module':
2:  - /usr/bin/python3 /home/william/ros2_ws/install/share/ament_lint_cmake/cmake/../../../bin/ament_lint_cmake --xunit-file /home/william/ros2_ws/build/connext_cmake_module/test_results/connext_cmake_module/lint_cmake.xml
2: -- run_test.py: verify result file '/home/william/ros2_ws/build/connext_cmake_module/test_results/connext_cmake_module/lint_cmake.xml'
2/2 Test #2: lint_cmake .......................   Passed    0.18 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =   0.38 sec

The following tests FAILED:
	  1 - copyright (Failed)
Errors while running CTest
make: *** [test] Error 8

Stopping with package 'connext_cmake_module'
```

**Comment by tfoote** [comment]
lgtm

**Comment by dirk-thomas** [comment]
The question is: do we want the output of each test to be printed to the console by default or not? Do we want an `ament` specific option to change the default behavior?

**Comment by esteve** [comment]
+1

**Comment by wjwwood** [comment]
Having it output by default is certainly convenient, but I think we should have an option to not pass extra options to `make test`. Then again we may not need it, can you try passing `ARGS=-V` or `ARGS=-VV` or something like that before `ament.py` with the patch proposed? It would be interesting to see the behavior of `ctest` when both mechanisms are provided. Personally I would be happy with only the other pr which has the test go to file and to screen (which is then captured by ctest), but I see the convenience of this one too.

**Comment by dirk-thomas** [comment]
I updated the PR to allow overriding the behavior by setting the ARGS env var.

**Comment by wjwwood** [comment]
+1

**Pull request merged**
